[package]
name = "scraper-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
scraper = "0.18.1"
thirtyfour = "0.32.0-rc.8"
tokio = "1.34.0"
